const AssetsSrc = {
    images: {
        businessIcon: '/assets/images/business.png',
        communityIcon: '/assets/images/community.png',
        crystalWhiteLarge: '/assets/images/crystal_white_large.png',
        crystalWhiteMedium: '/assets/images/crystal_white_medium.png',
        crystalWhiteSmall: '/assets/images/crystal_white_small.png',
        crystalsShadows: '/assets/images/crystals_shadows.png',
        diamondIcon: '/assets/images/diamond.png',
        downArrowIcon: '/assets/images/down-arrow.svg',
        githubIcon: '/assets/images/github.png',
        layersIcon: '/assets/images/layers.png',
        lenseWhiteLarge: '/assets/images/lense_white_large.png',
        lenseWhiteMedium: '/assets/images/lense_white_medium.png',
        lenseWhiteSmall: '/assets/images/lense_white_small.png',
        lumLogoTextWhite: '/assets/images/lum_logo_text_white.png',
        lumNetworkLogoDark: '/assets/images/lum_network_logo_dark.png',
        lumNetworkLogo: '/assets/images/lum_network_logo.png',
        notificationIllu: '/assets/images/notification_illu.png',
        poweredByLum: '/assets/images/power_by_the_lum.png',
        rewardBlueLarge: '/assets/images/reward_blue_large.png',
        rewardBlueMedium: '/assets/images/reward_blue_medium.png',
        rewardBlueSmall: '/assets/images/reward_blue_small.png',
        secureChain: '/assets/images/secure_chain.png',
        stakeEarn: '/assets/images/stake_earn.png',
        contentStamping: '/assets/images/store_content.png',
        traceabilityIcon: '/assets/images/traceability.png',
        transparencyIcon: '/assets/images/transparency.png',
        trustLayers: '/assets/images/trust_layers.png',
        trustLayersShadows: '/assets/images/trust_layers_shadows.png',
        showcaseLumkiIllu: '/assets/images/showcase_lumki_illu.png',
        showcaseNetreviewsIllu: '/assets/images/showcase_netreviews_illu.png',
        showcaseJoinIllu: '/assets/images/showcase_join_illu.png',
        mainnetIllu: '/assets/images/mainnet_illu.png',
    },
    partners: {
        tendermint: '/assets/images/partners/tendermint.png',
        skeepers: '/assets/images/partners/skeepers.png',
        arcanum: '/assets/images/partners/arcanum.png',
        swissborg: '/assets/images/partners/swissborg.png',
        stakefish: '/assets/images/partners/stakefish.png',
        cosmostation: '/assets/images/partners/cosmostation.png',
        klub: '/assets/images/partners/klub.png',
        imperator: '/assets/images/partners/imperator.png',
        sg1: '/assets/images/partners/sg-1.png',
        sentinel: '/assets/images/partners/sentinel.png',
        stakewithus: '/assets/images/partners/stakewithus.png',
        cryptocrew: '/assets/images/partners/cryptocrew.png',
    },
};

export default AssetsSrc;
