name: Automatically deploy the lum-network website updates to firebase hosting
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy on testnet hosting
    runs-on: ubuntu-latest
    environment: testnet
    steps:
      - name: Set up Node version to 14
        uses: actions/setup-node@v2
        with:
            node-version: '14'
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install packages
        run: yarn

      - name: Build
        run: yarn build
        env:
          SASS_PATH: "node_modules:src/styles"

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: lum-network
          target: lum-network-website