name: Automatically deploy the lum-network website updates to firebase hosting
on:
  push:
    branches:
      - master

jobs:
  build_deploy_testnet:
    name: Deploy the the built content on testnet hosting
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install packages
        run: yarn

      - name: Build
        run: yarn build
        env:
          SASS_PATH: "node_modules:src/styles"

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: lum-network
          target: lum-network-website

  build_deploy_mainnet:
    name: Deploy the the built content on main net hosting
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install packages
        run: yarn

      - name: Build
        run: yarn build
        env:
          SASS_PATH: "node_modules:src/styles"

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: lum-network
          target: lum-network
